apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-loader-api-new-pvc
  namespace: rpa-job-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: file-loader-api-new-pv